version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 9wV8u7fxGyAhENL93
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persisting database data
    networks:
      - share-network

  scheduler:
    container_name: scheduler
    image: vadimvlk/private:scheduler
    restart: always
    volumes:
      - /var/deribit/appsettings.json:/app/appsettings.json
    networks:
      - share-network
  web:
    container_name: web
    image: vadimvlk/private:web
    restart: always
    networks:
      - share-network
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
networks:
  share-network:
    driver: bridge

volumes:
  postgres_data:  # Volume to persist PostgresSQL data.
