// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Option.Data.Database;

#nullable disable

namespace Option.Data.Database.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511193319_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Option.Data.Shared.Poco.OptionData", b =>
                {
                    b.Property<double>("Strike")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Expiration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<double>("CallDelta")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("CallGamma")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("CallOi")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("CallPrice")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Iv")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("PutDelta")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("PutGamma")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("PutOi")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<double>("PutPrice")
                        .HasColumnType("decimal(18, 8)");

                    b.HasKey("Strike", "Expiration", "Type", "Currency");

                    b.HasIndex("Currency");

                    b.HasIndex("Expiration");

                    b.HasIndex("Strike");

                    b.HasIndex("Type");

                    b.ToTable("OptionData");
                });
#pragma warning restore 612, 618
        }
    }
}
